#!/bin/bash

if [ ! ${EUID:-$(id -u)} -eq 0 ]; then
    echo 'You must be root to run this script'
    exit 1
fi

HOME=$(eval echo ~${SUDO_USER:-$USER})
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

installdir="/usr/share/pywal-discord"

uname="$(uname -s)"

if [[ "$uname" == Darwin* ]]; then
    installdir="$XDG_CONFIG_HOME/pywal-discord"
fi

if [ -e "$installdir" ]; then
    rm -rf "$installdir"
fi

cp -r "./config/" "$installdir/"

if [[ "$uname" == Darwin* ]]; then
    cp ./pywal-discord /usr/local/bin/
else
    cp ./pywal-discord /usr/bin/
fi
